### PR TITLE
make code compile with tsc 4.4.3

### PR DESCRIPTION
**Pull request by 0815fox**
Newest version of tsc complains about two errors:

> lib/server.ts:228:30 - error TS2352: Conversion of type 'RawData' to type 'string' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
>   Type 'Buffer[]' is not comparable to type 'string'.
> 
> 228         message = JSON.parse(msg as string);
>                                  ~~~~~~~~~~~~~
> 
> lib/server.ts:277:30 - error TS2571: Object is of type 'unknown'.
> 
> 277                     message: e.message,

However, it needs to be discussed, if `msg as string` should be force-casted as I did for now, or if we better use the `toString` method. Did not find out, why, but the msg-Parameter not is of type `RawData` which is `Buffer | ArrayBuffer | Buffer[]` and not directly convertible to string anymore.

### CODE REVIEW

**Review by tim-hellhake — CHANGES_REQUESTED** [review]
`npm run prettier`

**Comment by 0815fox** [comment]
After running prettier on this branch there were no changes in the diff. Don't know why the build failed.
